title: Probability and Statistics Applications for Civil Engineers
author: Robert Lanzafame, Miguel Mendoza Lugo and Patricia Mares Nasarre
logo: logo sketch and tud.png

execute:
  execute_notebooks: false

launch_buttons:
  thebe: true

only_build_toc_files: true

sphinx:
  config:
    html_show_copyright: true
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
  extra_extensions:
    - sphinx.ext.imgconverter
    - download_link_replacer
    - jupyterbook_patches

html:
#  announcement: "⚠️ This is not the final version of the book! The new version will be ready by July 1.⚠️"
  home_page_in_navbar: false
  google_analytics_id: G-3M271KTT5T
  extra_navbar: |
      <div>
          <IMG SRC="https://raw.githubusercontent.com/mbakker7/exploratory_computing_with_python/master/tudelft_logo.png" WIDTH=200 ALIGN="center">
      </div>
#  use_issues_button: true
#  use_repository_button: true